apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: expense
  labels:
    app: frontend
    tier: frontend
    purpose: expense
spec: #replica set
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      tier: frontend
      purpose: expense
  template:  #pod template
    metadata:
      labels:
        app: frontend
        tier: frontend
        purpose: expense
    spec:
      containers:
      - name: nginx
        image: rushhav717/frontend:1.0.0
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: expense
spec:
  type: LoadBalancer
  selector:
        app: frontend
        tier: frontend
        purpose: expense
  ports:
    - protocol: TCP
      port: 80 #service port
      targetPort: 80

