apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  labels:
    app: backend
    tier: backend
    purpose: expense
spec: #replica set
  replicas: 1
  selector:
    matchLabels:
      app: backend
      tier: backend
      purpose: expense
  template:  #pod template
    metadata:
      labels:
        app: backend
        tier: backend
        purpose: expense
    spec:
      containers:
      - name: nginx
        image: rushhav717/backend:1.0.0
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: expense
spec:
  selector:
        app: backend
        tier: backend
        purpose: expense
  ports:
    - protocol: TCP
      port: 8080 #service port
      targetPort: 8080 
