apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
    tier: mysql
    purpose: expense
spec: #replica set
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      tier: mysql
      purpose: expense
  template:  #pod template
    metadata:
      labels:
        app: mysql
        tier: mysql
        purpose: expense
    spec:
      containers:
      - name: nginx
        image: rushhav717/mysql:1.0.0
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
        app: mysql
        tier: mysql
        purpose: expense
  ports:
    - protocol: TCP
      port: 3306 #service port
      targetPort: 3306 
